### ISSUE TITLE
Cannot run main.py

### ISSUE THREAD

**Issue by d-perez-1** [BioPhysicsUP/Full_SMS#21]
Issue trying to run software from source. Windows 10, python 3.9.

Created new environment and installed packages listed in installation instructions
https://up-biophysics-sms.readthedocs.io/en/latest/usage/installation.html

cloned source code from git hub

python main.py in \src directory gives the following error:

```
Currently used style: QWindowsVistaStyle
Available styles: ['windowsvista', 'Windows', 'Fusion']
2024-05-16 13:11:02,192 -> MainThread -> main -> main: App created
2024-05-16 13:11:02,192 -> MainThread -> main -> __init__: Multi-threading with maximum 8 threads
2024-05-16 13:11:02,192 -> MainThread -> main -> __init__: System -> Windows
Process Process-1:
Traceback (most recent call last):
  File "\miniconda3\envs\fullsms\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "\miniconda3\envs\fullsms\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "\Full_SMS\src\main.py", line 1526, in main
    main_window = MainWindow()
  File "\Full_SMS\src\main.py", line 146, in __init__
    self.spectra_controller = SpectraController(main_window=self)
  File "\Full_SMS\src\controllers.py", line 3188, in __init__
    self.main_window.pgSpectra_Image_View = pg.ImageView(view=pg.PlotItem(), roi=myPlotROI(size=(10, 200)))
TypeError: __init__() got an unexpected keyword argument 'roi'
```

**Comment by bvanheerden** [comment]
Hi, thanks for checking out our software! 
Can you confirm whether you are using the latest version of pyqtgraph, i.e. 0.13.7?

**Comment by d-perez-1** [comment]
That was the issue! Not sure why I ended up with an old version on a fresh install, but thanks for helping me fix it.
